events {}

worker_processes auto;

user raquib;

http {
    include mime.types;

    server {
        root /home/raquib/Code/Backend-Mastery/20-Deploying-Nodejs-Applications-and-CI-CD/08-Creating-Multiple-Servers-using-Nginx/backend;

        server_name api.local.com;

        listen 80;
    }
    server {
        root /home/raquib/Code/Backend-Mastery/20-Deploying-Nodejs-Applications-and-CI-CD/08-Creating-Multiple-Servers-using-Nginx/frontend;

        server_name local.com;

        listen 80;
    }
    autoindex on;
}