worker_processes 4;

events {}

http {
	server {
		root /home/raquib/Code/Backend-Mastery/20-Deploying-Nodejs-Applications-and-CI-CD/06-Nginx-Configuration-Deep-Dive/simple-website;
		# index index.nginx-debian.html;
	 }
}